#
# Copyright 2012-2019 CNRS-UM LIRMM, CNRS-AIST JRL
#

dist: xenial
addons:
  apt:
    packages:
    - doxygen
    - doxygen-latex
    - libboost-all-dev
    - libeigen3-dev
    - python-pip
    - python3-pip
    - cython
    - python-nose
    - python-numpy
    - python-coverage
    - cython3
    - python3-nose
    - python3-numpy
    - python3-coverage
    - python3-setuptools
branches:
  except:
    - debian
language: cpp
env:
  global:
    - CMAKE_ADDITIONAL_OPTIONS="-DPYTHON_BINDING_BUILD_PYTHON2_AND_PYTHON3:BOOL=ON -DPYTHON_BINDING_USER_INSTALL:BOOL=ON"
    - GIT_DEPENDENCIES="jrl-umi3218/Eigen3ToPython jrl-umi3218/SpaceVecAlg jrl-umi3218/sch-core"
  matrix:
    - CMAKE_BUILD_TYPE=RelWithDebInfo
    - CMAKE_BUILD_TYPE=Debug
script: ./.travis/run build
before_install:
- export CMAKE_ADDITIONAL_OPTIONS="${CMAKE_ADDITIONAL_OPTIONS} -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
- ./.travis/run  before_install
notifications:
  slack:
    secure: IF3wdWNp1d9lD/W39A3hY58Qu3mAz8QjcHA6FOITf6clcT49KaeHMtS13z5pK5MocuAE7fQouyJsAjy7DfY0gd+/jOJg5mx8vZat3t7Ro2ui2h5IyB2PGXQobTtl5EB4ncupg0uCOfDHfBYfVc1Jhq/bjXa8YR16YjmSU5+eCdw=
